### ISSUE TITLE
[4.0.0] Nav not moving out of viewport when position changes to hidden.

### ISSUE THREAD

**Issue by janpe** [iiroj/react-sticky-nav#2]
After updating to v4 the nav doesn't hide anymore when the position prop changes to hidden. Used the exact styles and content from the example.

Otherwise the props seem to work as expected and there aren't any extra rerenders anymore when the position prop changes. 👍

**Comment by iiroj** [comment]
Hello,

Can you post a video, or a more detailed description of how to reproduce this bug?

The `position: 'hidden'` is set only after the nav element _should_ be completely hidden. Technically this means that the `top: -X` style has been udpated to where `X` equals the height of the nav element.

I haven't been able to get it working incorrectly in:

* Safari 13.0.5
* Firefox 72.0.2
* Chrome 79

As a "debug" improvement, I'll add the current position status to the middle of the example page so that it's visible even when the nav element itself is fully hidden.

**Comment by iiroj** [comment]
I am seeing some weird behaviour on Safari, possibly related to overflow scrolling.

When scrolling to the end of the example page, instead of staying _hidden_ the `position` changes to _pinned_.

Could this be what you're experiencing?

**Comment by iiroj** [comment]
I released [v4.0.1](https://github.com/iiroj/react-sticky-nav/blob/master/CHANGELOG.md#401-2020-02-18) with updated dependencies, and an additional debug text in the example page:

**This is the unfixed state:**

<img width="320" alt="unfixed" src="https://user-images.githubusercontent.com/11628889/74726438-2039c000-5248-11ea-91b6-a2449c4a0cd9.png">

**This is the pinned state:**

<img width="320" alt="pinned" src="https://user-images.githubusercontent.com/11628889/74726447-26c83780-5248-11ea-8446-aab39e80fd0e.png">

**This is also pinned, but on its way to hidden:**

<img width="320" alt="still pinned" src="https://user-images.githubusercontent.com/11628889/74726455-2891fb00-5248-11ea-866c-8e7cfd2babb9.png">

**This is the hidden state, when it's completely out of view:**

<img width="320" alt="hidden" src="https://user-images.githubusercontent.com/11628889/74726459-29c32800-5248-11ea-8f7b-efd2e9e7b63d.png">

**Comment by janpe** [comment]
Not sure what is causing it but after v4 `top` for the sticky nav is always `0px`. I cloned this repo and tried the example and it was working fine.

**Comment by janpe** [comment]
Not sure how helpful it is but here's a clip.

[screen rec.zip](https://github.com/iiroj/react-sticky-nav/files/4234960/screen.rec.zip)

**Comment by iiroj** [comment]
From version 4 onwards the position style is updated via the `ref` instead of through React's render. This was a performance improvement.

Are you possibly using the `render` prop with a custom component? Make sure to pass the ref supplied via the prop:

```tsx
<ReactStickyNav
  render={({ position, ref }) => (
    <div ref={ref}> {/* make sure to pass `ref` to the element */}
      {`<ReactStickyNav />`} is currently {position} — Scroll up and down for demo
      <Position>Current position: {position}</Position>
    </div>
  }
/>
```

If you also need an external ref for the same custom component, that's also possible because ReactStickyNav combines them internally:

```tsx
const myExternalRef = React.useRef<HTMLDivElement>(null)
/* render */
<ReactStickyNav
  ref={myExternalRef}
  render={({ position, ref: combinedRef }) => (
    <div ref={combinedRef}> {/* make sure to pass `combinedRef ` to the element */}
      {`<ReactStickyNav />`} is currently {position} — Scroll up and down for demo
      <Position>Current position: {position}</Position>
    </div>
  }
/>
```

**Comment by janpe** [comment]
I'm not using the render prop. Trying to do a working dummy version using it exactly as in the example but still no luck.

**Comment by iiroj** [comment]
Very strange. Could it be an out-of-date React version? If upgrading React works, I'll release a fix for bumping the version requirement.

If all else fails, you can privately send me some debug code and I can take a look.

**Comment by janpe** [comment]
Everything is up to date. The nav element gets the class unfixed/hidden/pinned properly but top is always 0px.

**Comment by iiroj** [comment]
Using the `render` you can debug the current `top` value:

```js
<ReactStickyNav render={({ top, ref }) => (<div ref={ref}>current top value: {top}</div>)} />
```

This way we can know if the issue is with the `top` actually always being `0`, or that it's not setting the style correctly.

I think it would be easier if you sent a reproducible example so that I could debug it myself.

**Comment by janpe** [comment]
Trying it that way top is always undefined.

**Comment by iiroj** [comment]
Since the example in this repo worked for you, does it continue to work if you use it inside the project you’re building? Alternatively, does the non-working version still not work if transferred to the example in this repo?

I’m sorry but I don’t think I can debug further without some reproducible code I can test myself.

**Comment by janpe** [comment]
Did some debugging and it seems that `top` seems to be updated correctly inside `handleAnimateTop` but it always remains outside of it. Eg. inside `if (render) ...`.

**Comment by janpe** [comment]
Actually the same seems to be true in the example as well even though that one works as expected. But I am not using the render prop in these cases.

**Comment by janpe** [comment]
Actually even in the example `top` is always zero even when using the render prop and the functionality otherwise works as expected.

**Comment by iiroj** [comment]
Thanks for debugging. I believe that might be because the top value passed to the render prop (outside of `handleAnimate`) is mutable (from `React.useRef`), so even though its value changes, debugging tools or the component might not pick it up.

Because `handleAnimate` sets it directly via the `element.style.top` property, it still works in the example.

I'll add additional handling to make the render prop's `top`-value not be mutable, and let's hope it starts working.

**Comment by janpe** [comment]
Still puzzles me why the example works fine but I cannot get it to work in my Gatsy project when stripping pretty much everything else from the page to a point where it looks exactly like the example. 😅

**Comment by iiroj** [comment]
Hello again, please try `react-sticky-nav@4.0.2`. The `top` property passed to the `render` function prop should no longer be mutable. This means it won't be as effective since it goes through React's reconciliation, but maybe it works.

I will also test setting up a plain gatsby starter project to see if it contains something that would break this package.

**Comment by iiroj** [comment]
I'll close this as inactive.
